main.py, models/github/event_type.py, slack_bot/runner.py, utils/storage.py
=> fix: Fix several small bugs.

README.md
* Include info about git hooks
* Raise Python version
=> docs: Update `README`.

README.md, bot_manifest.yml, main.py
=> docs: Add installation instructions.

bot/github/github_parsers.py, bot/slack/messenger.py
=> feat: Show user who starred/unstarred.

bot/slack/messenger.py
=> fix(slack): Disable unfurling of media links.

bot/github/github_parsers.py
=> fix: Fix branch name extraction code.

bot/github/github_parsers.py, bot/models/github/event.py, bot/slack/messenger.py, main.py, tests/github/data.json, tests/github/test_github_parsers.py, tests/utils/deserializers.py, tests/utils/load.py, tests/utils/serializers.py
=> test: Add demonstrative unittests and file structure.

bot/models/github/commit.py, bot/models/github/event.py, bot/models/slack.py
=> chore: add  __str__ methods

bot/models/github/event.py, tests/github/data.json
=> chore: Do not initialize unnecessary attributes in `GitHubEvent`.

bot/github/github_parsers.py, bot/models/github/event.py, tests/github/data.json, tests/utils/serializers.py
=> test: Add unittests for github_parsers.

bot/github/github_parsers.py, tests/github/test_github_parsers.py
=> fix(github): Format Github links correctly into Slack format.

.dockerignore, .gitignore, bot/utils/log.py, bot/utils/storage.py, docker-compose.yml
=> build: Extract storage to Docker volume.

bot/slack/runner.py, tests/slack/data.json
=> fix(slack): Make "no subscriptions" message ephemeral

bot/slack/runner.py
=> feat(slack): Add apt response for empty unsubscribe

bot/slack/runner.py
=> feat: Add quiet message.

bot/slack/runner.py
=> chore(slack): Change commands.

bot/slack/runner.py
=> feat(slack): Put constraint on syntax of repository name.

bot/slack/bot.py, bot/slack/runner.py, main.py
=> feat(slack): Make Slack signing secret mandatory

bot/github/authenticator.py
=> feat(github): Clarify Web-hook creation error.

bot/github/authenticator.py, bot/github/base.py, bot/github/parser.py, bot/slack/runner.py, bot/storage/__init__.py, bot/storage/github.py, bot/storage/secrets.py, main.py
=> feat: Store mapping from Slack user id to GitHub username.

tests/slack/data.json, tests/slack/test_runner.py
=> test: Add unittest for `/sel-list q`
